# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff2044233f0684b243e91b30360a59f7ce366b379ddf0b3ac066ac3d2069fc804d6d43ce3caed6c14205ec9c47dd9c6a247a14f4046ecd40cc880232b9960e59

test:
  secret_key_base: 091ddf947e7c1709cce793854cc04bd3616d59535bd52a4ef06be65151006a17bc28caa792ea6bc523b24c4150b4613696fedcb7c87acf1d6e0e64c5aa9e774e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
